const https = require('https');
const EventEmitter = require('events');
const logger = require('./logger');

/**
 * 📱 Real-Time iPhone -> Desktop Task Synchronization Engine
 * Listens to ntfy.sh stream via SSE/HTTP stream for instant task creation from iOS.
 */

class NtfySubscriber extends EventEmitter {
  constructor(topic = 'nova-my-tasks') {
    super();
    this.topic = topic;
    this.req = null;
    this.processedIds = new Set();
    this.isListening = false;
    this.reconnectTimeout = null;
  }

  setTopic(topic) {
    if (topic && topic.trim() && topic.trim() !== this.topic) {
      this.topic = topic.trim();
      this.stop();
      this.start();
    }
  }

  start() {
    if (this.isListening || !this.topic || this.topic === 'none') return;

    try {
      const url = `https://ntfy.sh/${encodeURIComponent(this.topic)}/json?since=10m`;
      logger.info(`[iPhone Sync] Connecting real-time task listener to ${url}...`);

      this.req = https.get(url, (res) => {
        if (res.statusCode !== 200) {
          logger.warn(`[iPhone Sync] ntfy stream returned status ${res.statusCode}. Retrying in 10s...`);
          this.scheduleReconnect();
          return;
        }

        this.isListening = true;
        logger.info(`[iPhone Sync] 🟢 Connected! Listening for incoming tasks from iPhone on topic "${this.topic}"`);

        let buffer = '';

        res.on('data', (chunk) => {
          buffer += chunk.toString('utf-8');
          const lines = buffer.split('\n');
          buffer = lines.pop(); // Keep incomplete line in buffer

          for (const line of lines) {
            if (!line.trim()) continue;
            try {
              const msg = JSON.parse(line.trim());

              // Only process 'message' events
              if (msg.event === 'message' && msg.id && msg.message) {
                // Deduplicate by message ID
                if (this.processedIds.has(msg.id)) continue;
                this.processedIds.add(msg.id);

                // Prevent memory leak in processedIds set (keep last 200 IDs)
                if (this.processedIds.size > 200) {
                  const firstId = this.processedIds.values().next().value;
                  this.processedIds.delete(firstId);
                }

                // Ignore outbound notifications generated by Nova app/PowerShell
                const title = msg.title || '';
                const isNovaOutbound = title.startsWith('🔔') || 
                                       title === 'Task Reminder' || 
                                       msg.message.startsWith('Time: ') || 
                                       msg.message.startsWith('Priority: ');

                if (!isNovaOutbound) {
                  const taskInputText = msg.message.trim();
                  logger.info(`[iPhone Sync] 📱 Received task from iPhone: "${taskInputText}" (ID: ${msg.id})`);
                  this.emit('task-received', {
                    id: msg.id,
                    text: taskInputText,
                    timestamp: msg.time
                  });
                }
              }
            } catch (err) {
              // Ignore ping/heartbeat non-JSON lines
            }
          }
        });

        res.on('end', () => {
          this.isListening = false;
          logger.info('[iPhone Sync] ntfy stream closed. Reconnecting in 5s...');
          this.scheduleReconnect(5000);
        });

        res.on('error', (err) => {
          this.isListening = false;
          logger.error(`[iPhone Sync] ntfy stream error: ${err.message}`);
          this.scheduleReconnect(5000);
        });
      });

      this.req.on('error', (err) => {
        this.isListening = false;
        logger.error(`[iPhone Sync] Request connection error: ${err.message}`);
        this.scheduleReconnect(10000);
      });

    } catch (err) {
      this.isListening = false;
      logger.error(`[iPhone Sync] Failed to start ntfy subscriber: ${err.message}`);
      this.scheduleReconnect(10000);
    }
  }

  scheduleReconnect(delayMs = 5000) {
    this.stop();
    if (this.reconnectTimeout) clearTimeout(this.reconnectTimeout);
    this.reconnectTimeout = setTimeout(() => {
      this.start();
    }, delayMs);
  }

  stop() {
    this.isListening = false;
    if (this.reconnectTimeout) {
      clearTimeout(this.reconnectTimeout);
      this.reconnectTimeout = null;
    }
    if (this.req) {
      try {
        this.req.destroy();
      } catch (e) {}
      this.req = null;
    }
  }
}

module.exports = NtfySubscriber;
